name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.5.0+1
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800

    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500

    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
          weight: 700


    - family: dana
      fonts:
        - asset: assets/fonts/dana.ttf
          weight: 500